import { NextResponse } from 'next/server';
import { z } from 'zod';
import { createRoom, joinRoom, restoreRoom } from '@/lib/store';
import { provider } from '@/lib/llm';
import { supabase } from '@/lib/supabase';
const schema=z.object({action:z.enum(['create','join']),code:z.string().regex(/^\d{6}$/,'请输入六位数字邀请码').optional(),nickname:z.string().min(1).max(20),theme:z.string().max(40).optional(),difficulty:z.enum(['easy','normal','hard']).optional()});
export async function POST(req:Request){ try{const b=schema.parse(await req.json()); if(b.action==='create'){const x=createRoom(b.theme||'悬疑',b.difficulty||'normal',b.nickname); if(process.env.NEXT_PUBLIC_SUPABASE_URL){const {error}=await supabase.from('rooms').insert({id:x.room.id,room_code:x.room.code,host_player_id:x.playerId,status:'waiting',theme:x.room.theme,difficulty:x.room.difficulty}); if(error)throw error; await supabase.from('players').insert({id:x.playerId,room_id:x.room.id,nickname:b.nickname,is_host:true});} return NextResponse.json({code:x.room.code,playerId:x.playerId,room:x.room});}
if(process.env.NEXT_PUBLIC_SUPABASE_URL){const {data:db,error}=await supabase.from('rooms').select('*').eq('room_code',b.code).single();if(error||!db)throw Error('邀请码不存在');if(db.status==='finished')throw Error('本局已结束，请让房主创建新房间');const {data:existing}=await supabase.from('players').select('nickname').eq('room_id',db.id).eq('nickname',b.nickname).maybeSingle();if(existing)throw Error('昵称已被使用');const playerId=crypto.randomUUID();const {error:insertError}=await supabase.from('players').insert({id:playerId,room_id:db.id,nickname:b.nickname,is_host:false});if(insertError)throw insertError;const {data:players}=await supabase.from('players').select('id,nickname,is_host').eq('room_id',db.id);const hydrated=restoreRoom({id:db.id,code:db.room_code,hostId:db.host_player_id,status:db.status,theme:db.theme,difficulty:db.difficulty,story:db.story_data||undefined,hintIndex:0,players:(players||[]).map(p=>({id:p.id,nickname:p.nickname,isHost:p.is_host})),questions:[],createdAt:db.created_at});return NextResponse.json({code:hydrated.code,playerId,room:hydrated});}
const x=joinRoom(b.code||'',b.nickname); return NextResponse.json({code:x.room.code,playerId:x.playerId,room:x.room});}catch(e:any){return NextResponse.json({error:e.message||'请求失败'},{status:400});}}
