'use client';
import { useEffect, useState } from 'react';
import { supabaseBrowser } from '../lib/supabase-browser';
type Room = any;
export default function Home(){
 const [screen,setScreen]=useState<'home'|'room'>('home'),[room,setRoom]=useState<Room>(),[code,setCode]=useState(''),[pid,setPid]=useState(''),[name,setName]=useState(''),[theme,setTheme]=useState('随机'),[q,setQ]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const leave=(msg='')=>{localStorage.removeItem('turtle-code');localStorage.removeItem('turtle-player');setScreen('home');setRoom(undefined);setCode('');setPid('');setError(msg);history.replaceState(null,'','/')};
 useEffect(()=>{if(screen!=='room'||!code)return;let cancel=false;const sync=async()=>{const r=await fetch(`/api/rooms/${code}`,{cache:'no-store'});if(r.status===404)return !cancel&&leave('房间已失效');if(r.ok){const d=await r.json(),x=await fetch(`/api/rooms/${code}/questions`,{cache:'no-store'});if(!cancel)setRoom({...d.room,questions:x.ok?(await x.json()).questions:[]})}};sync();const channel=supabaseBrowser.channel(`turtle-${code}`).on('postgres_changes',{event:'*',schema:'public',table:'rooms'},sync).on('postgres_changes',{event:'*',schema:'public',table:'players'},sync).on('postgres_changes',{event:'*',schema:'public',table:'questions'},sync).subscribe();return()=>{cancel=true;supabaseBrowser.removeChannel(channel)}},[screen,code]);
 useEffect(()=>{document.querySelectorAll('option').forEach(option=>{if(option.textContent==='温暖'||option.value==='温暖'){option.textContent='红汤';option.value='红汤';option.label='红汤'}});document.querySelectorAll('select').forEach(select=>{if(select.value==='温暖')select.value='红汤'})});
 useEffect(()=>{if(screen!=='room'||!code||room?.status!=='playing')return;let seconds=60;const button=document.createElement('button');button.className='hint-fab hint-waiting';button.disabled=true;button.textContent=`提示将在 ${seconds} 秒后出现`;const timer=setInterval(()=>{seconds--;button.textContent=seconds>0?`提示将在 ${seconds} 秒后出现`:'获取提示';if(seconds<=0){clearInterval(timer);button.disabled=false;button.classList.remove('hint-waiting');button.onclick=async()=>{const r=await fetch(`/api/rooms/${code}/hint`,{method:'POST'}),d=await r.json();alert(r.ok?`提示：${d.hint}`:d.error)}}},1000);document.body.append(button);return()=>{clearInterval(timer);button.remove()}},[screen,code,room?.status]);
 const enter=async(action:'create'|'join')=>{setBusy(true);setError('');const r=await fetch('/api/rooms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,code:action==='join'?code:undefined,nickname:name||'玩家',theme,difficulty:'normal'})}),d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);setRoom(d.room);setCode(d.code);setPid(d.playerId);setScreen('room');localStorage.setItem('turtle-code',d.code);localStorage.setItem('turtle-player',d.playerId);if(action==='create'){const s=await fetch(`/api/rooms/${d.code}/start`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerId:d.playerId})}),j=await s.json();if(s.ok)setRoom(j.room);else setError(j.error)}};
 const reroll=async()=>{const selected=await new Promise<string|null>(resolve=>{const shade=document.createElement('div');shade.className='theme-picker';const panel=document.createElement('div');panel.className='theme-picker-panel';panel.innerHTML='<b>下一题想玩什么？</b><p>选择题目类型</p>';const choices=['随机','悬疑','催泪','红汤'];choices.forEach(item=>{const button=document.createElement('button');button.textContent=item;button.onclick=()=>{shade.remove();resolve(item)};panel.append(button)});const cancel=document.createElement('button');cancel.textContent='取消';cancel.className='theme-picker-cancel';cancel.onclick=()=>{shade.remove();resolve(null)};panel.append(cancel);shade.append(panel);document.body.append(shade)});if(!selected)return;setTheme(selected);setBusy(true);const r=await fetch(`/api/rooms/${code}/reroll`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerId:pid,theme:selected})}),d=await r.json();setBusy(false);if(r.ok)setRoom(d.room);else setError(d.error)};
 const ask=async()=>{if(!q||busy)return;setBusy(true);const r=await fetch(`/api/rooms/${code}/questions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerId:pid,content:q})}),d=await r.json();setBusy(false);if(r.ok){setRoom({...room,questions:[...(room.questions||[]),d.question]});setQ('')}else setError(d.error)};
 const reveal=async()=>{const r=await fetch(`/api/rooms/${code}/finish`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerId:pid})}),d=await r.json();if(r.ok)setRoom(d.room);else setError(d.error)};
 if(screen==='home')return <main className="min-h-screen flex items-center justify-center p-6"><div className="w-full max-w-xl rounded-3xl bg-slate-900 p-8"><h1 className="text-4xl font-bold mb-2">海龟汤</h1><p className="text-slate-400 mb-6">创建后会随机生成六位邀请码。</p><input className="w-full p-3 rounded bg-slate-800 mb-3" value={name} onChange={e=>setName(e.target.value)} placeholder="昵称（可不填）"/><select className="w-full p-3 rounded bg-slate-800 mb-4" value={theme} onChange={e=>setTheme(e.target.value)}><option>随机</option><option>悬疑</option><option>催泪</option><option>温暖</option></select><button disabled={busy} className="w-full p-4 rounded bg-cyan-500 text-slate-950 font-bold" onClick={()=>enter('create')}>{busy?'正在创建…':'创建房间'}</button><div className="mt-8 pt-5 border-t border-slate-700"><b>加入房间</b><div className="flex gap-2 mt-3"><input inputMode="numeric" maxLength={6} className="flex-1 p-3 rounded bg-slate-800 font-mono tracking-[.2em]" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="六位邀请码"/><button className="px-5 rounded bg-slate-700" onClick={()=>/^\d{6}$/.test(code)?enter('join'):setError('请输入六位数字邀请码')}>加入</button></div></div>{error&&<p className="text-red-400 mt-4">{error}</p>}</div></main>;
 const playing=room?.status==='playing',finished=room?.status==='finished',host=room?.hostId===pid;return <main className="min-h-screen p-6"><div className="max-w-4xl mx-auto"><header className="flex justify-between mb-5"><button className="bg-slate-700 px-3 py-2 rounded" onClick={()=>leave()}>← 首页</button><span>{room?.players?.length||1} 位玩家</span></header><div className="flex justify-between items-center rounded-xl bg-cyan-950/40 border border-cyan-500/40 p-4 mb-5"><span>房间邀请码</span><button className="font-mono text-2xl font-bold tracking-[.25em] text-cyan-300" onClick={()=>navigator.clipboard.writeText(code)}>{code}</button></div><section className="bg-slate-900 rounded-2xl p-6">{(playing||finished)?<><div className="flex justify-between"><h1 className="text-2xl font-bold">汤面</h1>{host&&!finished&&<div className="flex gap-2"><button disabled={busy} className="bg-slate-700 px-3 rounded" onClick={reroll}>{busy?'换题中…':'换一个汤面'}</button><button className="bg-amber-500 text-slate-950 px-3 rounded" onClick={reveal}>公开汤底</button></div>}</div><p className="text-lg leading-8 my-5">{room.publicSurface||room.story?.surface}</p>{finished&&<div className="p-4 mb-5 border border-amber-400 rounded"><b>汤底已公开</b><p className="mt-2">{room.revealedStory?.truth||room.story?.truth}</p>{host&&<button className="mt-4 bg-cyan-500 text-slate-950 px-4 py-2 rounded" onClick={reroll}>下一题</button>}</div>}{playing&&<div className="flex gap-2"><input className="flex-1 bg-slate-800 p-3 rounded" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="输入你的问题"/><button className="bg-cyan-500 text-slate-950 px-5 rounded" onClick={ask}>提问</button></div>}<div className="mt-6 space-y-3">{(room.questions||[]).map((x:any)=><div key={x.id}>{x.nickname}：{x.content}<b className="ml-3 text-cyan-300">{x.answerType}</b></div>)}</div></>:<p>正在生成新汤面…</p>}</section>{error&&<p className="text-red-400 mt-4">{error}</p>}</div></main>
}
